### ISSUE TITLE
As a user I want to have a game mode, where I am guessing film's income

### ISSUE THREAD

**Issue by chechmek** [sopra-fs23-group-14/sopra-fs23-group-14-server#11]
Development tasks:
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-server#30
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-server#31
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-client#7

Acceptance criteria:
- [ ] During the each round of the game both players see one film and guess its income
- [ ] At the end of each round players choices are displayed
- [ ] Users are able to choose the mode while creating the new game
