### ISSUE TITLE
As a user I want to have a nice UI/UX design in order to have good user experience

### ISSUE THREAD

**Issue by chechmek** [sopra-fs23-group-14/sopra-fs23-group-14-server#12]
Development tasks:
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-client#14
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-client#9
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-client#8

Acceptance criteria:
- [ ] During usage of the app user sees design as defined in mockups
- [ ] App has same design style on every page
