### ISSUE TITLE
As a user I want to have invite system between players in order to play game with other players

### ISSUE THREAD

**Issue by chechmek** [sopra-fs23-group-14/sopra-fs23-group-14-server#13]
Development tasks:
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-server#24
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-client#10
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-server#26

Acceptance criteria:
- [ ] Players see their pending invitaions on overview screen
- [ ] Players can accept invitaions by clicking on them or going to specific link
