### ISSUE TITLE
As a user I want to have a specified point distribution system in order to have a fair game

### ISSUE THREAD

**Issue by chechmek** [sopra-fs23-group-14/sopra-fs23-group-14-server#53]
Development tasks:
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-server#54
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-server#55
- [ ] sopra-fs23-group-14/sopra-fs23-group-14-client#12

Acceptance criteria:
- [ ] At the end of each game both players receive their respective amount of points
- [ ] Point distribution system is described on frontend page
- [ ] Timestamps of made choice are considered into point computation
